# 1.张量的创建

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
"""创建0维张量(标量)"""
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
"""创建1维张量"""
tf.constant([1.0, 2.0, 3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [7]:
"""创建2维张量"""
tf.constant([[1, 2],
             [3, 4],
             [5, 6]], dtype = tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

# 2.转化成numpy

In [8]:
tensor1 = tf.constant([1, 2, 3, 4, 5])

In [9]:
tensor1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [10]:
np.array(tensor1) # 第一种方法

array([1, 2, 3, 4, 5])

In [11]:
tensor1.numpy() # 第二种方法

array([1, 2, 3, 4, 5])

# 3.张量的常用函数

## （1）基本数学运算（加法，元素乘法，矩阵乘法）

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b), "\n") # 计算张量的和
print(tf.multiply(a, b), "\n") # 计算张量的元素乘法
print(tf.matmul(a, b), "\n") # 计算乘法

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



## （2）各种聚合运算

In [13]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
# 最大值
print(tf.reduce_max(c))
# 最大值索引
print(tf.argmax(c))
# 计算均值
print(tf.reduce_mean(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(5.0, shape=(), dtype=float32)


# 4.变量

In [14]:
var = tf.Variable([[1, 2], [3, 4]])

In [15]:
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [16]:
var.shape

TensorShape([2, 2])

In [17]:
var.dtype

tf.int32

In [18]:
var.numpy()

array([[1, 2],
       [3, 4]])

In [19]:
# 更改数值
var.assign([[2, 3], [4, 5]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>